rename current_term to latest term
everypolitician/everypolitician-popolo pull request #115
Opened 2016-10-25 14:13 UTC by struan

This changes `current_legislature` and `current_term` to `latest_legislature` and `latest_term` while leaving the `current_` versions but notes that they are deprecated.

Fixes #78

2016-10-25 15:09 UTC, tmtmtmtm requested changes

2016-10-25 15:09 UTC, tmtmtmtm commented on CHANGELOG.md
> +## [0.8.0] - 2016-09-26
Don't forget to bump `version.rb` as well…

2016-10-25 15:09 UTC, tmtmtmtm commented on CHANGELOG.md
> +  but it is not guaranteed that the term will be a concurent one. You
Is "concurrent" the right word here?

2016-10-25 15:09 UTC, tmtmtmtm commented on test/everypolitician/popolo/json_test.rb
> +    assert_equal popolo_json.latest_term, popolo_json.latest_legislative_period
probably worth leaving at least one test with the `current_` form too, just to make sure it's still working (and to be able to hook into once we start emitting deprecation warnings…)

2016-10-25 16:07 UTC, tmtmtmtm requested changes
I suspect there are a few other things that we need to include in this Changelog as well that have been added since the last release (we should really get better at remembering to add those as we go…)

2016-10-25 16:07 UTC, tmtmtmtm commented on CHANGELOG.md
> +## [0.8.0] - 2016-09-26
Oh, you also need to remember to add the line to the bottom of the file to make that `[…]` a valid target. (Sorry for not spotting that first time around).

2016-10-26 13:14 UTC, struan commented
I've added in what I think are all the changes but since we didn't tag the 0.7.0 release it's a bit hard to say exactly what's in there.

2016-10-27 17:08 UTC, tmtmtmtm requested changes

2016-10-27 17:08 UTC, tmtmtmtm commented on CHANGELOG.md
> +- `Collection.where` now returns a `Collection` rather and an `Array`
presumably this should be 'rather than'?

2016-10-27 17:08 UTC, tmtmtmtm commented on CHANGELOG.md
> +  - `Membership.legislative_period` or `Memberships.term`
presumably 'Membership' rather than 'Memberships' in the second one there?

2016-10-27 17:18 UTC, tmtmtmtm commented
@struan: this also has conflicts…

2016-10-28 06:51 UTC, tmtmtmtm commented
@struan: I've fixed those typos, and resolved the conflict with the `legislative_periods.max_by(&:start_date)`. I think this is good to go now! 👍

2016-10-28 06:54 UTC, tmtmtmtm approved these changes

2016-10-28 06:55 UTC, merged