WIP Add real methods to Organisation class
everypolitician/everypolitician-popolo pull request #57
Opened 2016-09-09 16:44 UTC by ondenman

Methods are currently created dynamically by Entity initialiser. Adding the following attr_reader methods to Organization class:

Properties are set in the class initializer.

Also a private method for retrieving identifier id from identifiers given the name of the scheme:

2016-09-13 06:50 UTC, tmtmtmtm commented
> Adding the following attr_reader methods to Organization class:
> Properties are set in the class initializer.

@ondenman as a general rule here (and elsewhere), I think I'd prefer that the actual work happens in real methods, and the initializer only sets up the underlying data. Granted, shoehorning these all into `attr_reader`s doesn't push a _lot_ of extra work into the constructor, but it's work that doesn't _need_ to be in the constructor (i.e. it's not actually about constructing the object, and setting these on the object seems like fairly needless duplication and bloat for no real benefit), so it's better to defer these until requested.

2016-09-14 20:30 UTC, tmtmtmtm requested changes
As with #56, I think the tests for this need to be against real data.

2016-09-30 10:41 UTC, tmtmtmtm requested changes
I think there also needs to be tests for as many as possible of the cases where these methods _don't_ return anything. We certainly expect that every organization will have a `name`, but many won't have `other_names`, for example.

2016-09-30 10:41 UTC, tmtmtmtm commented on lib/everypolitician/popolo/organization.rb
> +      def initializer(document)
what is this method for? Is this meant to be `initialize`? If so, you shouldn't need this, as it will inherit it from `Entity`

2016-09-30 10:41 UTC, tmtmtmtm commented on lib/everypolitician/popolo/organization.rb
> +      def identifier(scheme_name)
This already exists in `Entity`

2016-09-30 10:41 UTC, tmtmtmtm commented on lib/everypolitician/popolo/organization.rb
> +        document[:other_names]
I don't think we can return list elements like this "as-is".

2016-09-30 10:41 UTC, tmtmtmtm commented on test/everypolitician/popolo/organization_test.rb
> +    @organization ||= organizations.select { |o| o.id == 'MHP' }.first
I think you'd be better always going through the published interface for `find_by` or `where` instead of rolling your own `select`s

2016-09-30 10:41 UTC, tmtmtmtm commented on test/everypolitician/popolo/organization_test.rb
> +    @organization_with_seats ||= organizations.select { |o| o.classification == 'legislature' }.first
ditto here.

2016-10-06 15:51 UTC, struan commented
Closed in favour of https://github.com/everypolitician/everypolitician-popolo/pull/83

2016-10-06 15:51 UTC, closed without merging