WIP Add real methods
everypolitician/everypolitician-popolo pull request #60
Opened 2016-09-14 14:22 UTC by ondenman

Adds real methods to class to replace methods dynamically generated in Entity:

2016-09-14 14:22 UTC, ondenman commented
Not sure whether .contact() is supposed to be public facing. (https://github.com/everypolitician/everypolitician-popolo/blob/54-add-real-methods-to-person-class/test/everypolitician/popolo/person_test.rb) It’s called in the test: https://github.com/everypolitician/everypolitician-popolo/blob/54-add-real-methods-to-person-class/test/everypolitician/popolo/person_test.rb but I assume it’s meant to be private.

2016-09-15 15:13 UTC, tmtmtmtm requested changes
- This still has "WIP" in the title
- I'm a little uncomfortable with this removing all the existing tests. Adding _new_ tests against live data is a very good thing, but we're losing tests now (for example there are now only `assert_nil` tests for honorifics — i.e. none that actually show that the method works in cases where someone _does_ have those.
- You've made methods private that are used externally, e.g. in https://github.com/everypolitician/everypolitician-data/blob/master/rake_build/generate_final_csvs.rb

2016-09-30 10:48 UTC, tmtmtmtm requested changes
I'm still also very scared by the changes to the existing test. Ideally that test file should have zero changes so we can see that you're introducing any breaking behaviour — all the tests you're adding against real data should exist in a new test file. 

I think you also need negative tests for as many cases as possible (i.e where someone doesn't _have_ a `gender` field set, etc.)

2016-09-30 10:48 UTC, tmtmtmtm commented on lib/everypolitician/popolo/person.rb
> +      def identifiers
This one already lives in the parent class.

2016-09-30 10:48 UTC, tmtmtmtm commented on lib/everypolitician/popolo/person.rb
> +        document[:images]
Things that return lists are going to need to a little more complex than this, I suspect.

2016-09-30 10:48 UTC, tmtmtmtm commented on lib/everypolitician/popolo/person.rb
> +        document[:name]
This one will need to also cope with the case of someone actually having a `sort_name` field set.

2016-09-30 10:48 UTC, tmtmtmtm commented on lib/everypolitician/popolo/person.rb
> +        identifiers.find { |i| i[:scheme] == scheme_name }[:identifier] rescue nil
This one already exists in the parent class.

2016-09-30 10:48 UTC, tmtmtmtm commented on lib/everypolitician/popolo/person.rb
> +      def link(type)
Why is this one private?

2016-09-30 10:49 UTC, tmtmtmtm commented
@ondenman feel free to break this (and the parallel one for Organization) up into multiple PRs. There are a lot of issues here, so feel free to pick off the new methods in bunches, rather than trying to add so many in one shot (especially as you're not being complete anyway)

2016-09-30 15:51 UTC, ondenman commented
Started a new branch and PR: https://github.com/everypolitician/everypolitician-popolo/pull/82

2016-09-30 15:51 UTC, closed without merging