Add LegislativePeriod and LegislativePeriods classes
everypolitician/everypolitician-popolo pull request #75
Opened 2016-09-28 09:45 UTC by ondenman

LegislativePeriod subclasses from Event. LegislativePeriods subclasses from collection.
LegislativePeriod is an entity of LegislativePeriods.

Part of: #67

2016-09-29 09:34 UTC, tmtmtmtm requested changes
This approach worries me a little. It's plausible that it could be a good enough first step (though I think I'd still want to pre-filter rather than post-filter so we don't ever create bad objects, even to throw them away again instantly), but I think there's a slightly deeper question about what we want the workflow to be here generally. Do we want to be able able to instantiate Terms and Events directly? If so, what should happen if you give them data of the wrong type? Or, should we have a factory method on `Event` which gives you back the correct object? (And if so, should that just be `new`, or something else). Or some other approach entirely? @chrismytton any thoughts?

2016-09-29 09:34 UTC, tmtmtmtm commented on lib/everypolitician/popolo.rb
> +                                                   .sort_by(&:start_date)
This is a little bit inside-out. Essentially this is creating invalid objects and then removing them (i.e. it will generate LegislativePeriod objects for Elections and then `where` them out).

This largely _works_ (FSVO), but it's a bit of a warning sign. If, for example, we were to put a warning in the constructor of a Term complaining if the data you've passed it actually _isn't_ one, then this would spit out lots and lots of warnings every time.

2016-09-29 09:34 UTC, tmtmtmtm commented on test/everypolitician/popolo/json_test.rb
>  end
I think I'd want to be a bit more explicit here and test that _every_ element of `terms` is the correct object. I'd probably also want to test that everything that we know _is_ a term gets returned from here.

2016-09-29 13:44 UTC, chrismytton commented
> Do we want to be able able to instantiate Terms and Events directly? If so, what should happen if you give them data of the wrong type? Or, should we have a factory method on Event which gives you back the correct object? (And if so, should that just be new, or something else). Or some other approach entirely?

I think we should probably print a warning if you try to instantiate a `LegislativePeriod` with a hash that has something other than `'legislative period'` as the `classification`. I'm not so convinced about having a factory method on `Event` though. If a user wants to get a list of terms they can use `popolo.legislative_periods` or `popolo.terms`. In the future when we add methods for elections they can use `popolo.elections` etc. If a user wants a list of _all_ events of _any_ classification they can use `popolo.events`.

So I think the best thing to do would be to change [`Everypolitician::Popolo::JSON#events`](https://github.com/everypolitician/everypolitician-popolo/blob/35840acf9fc4ce5e7d74c9e9598bcc019aea53ef/lib/everypolitician/popolo.rb#L45-L47) so that it returns a list of `LegislativePeriod` _and_ `Event` instances. In the future, when we have elections as well, we can potentially make `Event` an abstract class.

2016-09-29 13:59 UTC, ondenman commented
@chrismytton The creation of these classes is intended to be a step towards: https://github.com/everypolitician/everypolitician-popolo/pull/61#discussion_r79657361

2016-09-29 14:04 UTC, chrismytton commented
> @chrismytton The creation of these classes is intended to be a step towards: #61 (comment)

Ah yes, I'd forgotten about that pull request as it wasn't linked to in the description of this one 😉

2016-09-30 10:26 UTC, tmtmtmtm commented
I'm not sure I like the weird limbo state where you can have plain Events or proper Terms. I'd be inclined to add both subclasses at the same time, make sure `legislature.events` returns the correctly instantiated elements (though whether the detection should be there, or in the Event class, I'm not so sure), and then have `legislature.terms` and `legislature.elections` do a `.where` on an internal `.events`

2016-09-30 15:41 UTC, struan commented
I am a bit concerned I have gone off the deep end with this :/

2016-10-03 10:10 UTC, chrismytton commented
I think this is a bit _too_ magical at the moment. I've done an experimental change here - https://github.com/everypolitician/everypolitician-popolo/compare/create-term-classes...create-term-classes-refactor - which (ab)uses the `entity_class` method to do dynamic class lookup. I'm still not 100% convinced that it's the right approach, but it relies on less meta-programming magic, so I think it or something similar is probably preferable.

2016-10-03 10:10 UTC, chrismytton requested changes
I think this is a bit _too_ magical at the moment. I've done an experimental change here - https://github.com/everypolitician/everypolitician-popolo/compare/create-term-classes...create-term-classes-refactor - which (ab)uses the `entity_class` method to do dynamic class lookup. I'm still not 100% convinced that it's the right approach, but it relies on less meta-programming magic, so I think it or something similar is probably preferable.

2016-10-05 13:00 UTC, struan commented
Closing in favour of https://github.com/everypolitician/everypolitician-popolo/pull/86

2016-10-05 13:00 UTC, closed without merging