Create EntityWithDynamicMethods class
everypolitician/everypolitician-popolo pull request #88
Opened 2016-10-04 15:59 UTC by ondenman

As a step towards implementing real methods in Entity subclasses, we are
moving dynamic method generation over to the EntityWithDynamicMethods Entity
subclass. Dynamic method generation is removed from Entity.

All Entity subclasses now inherit from this as a stopgap -- classes will revert
back to inheriting from Entity once they implement their own real methods. When all
these subclasses use real methods, EntityWithDynamicMethods can be removed.

References: https://github.com/everypolitician/everypolitician-popolo/issues/54

2016-10-05 08:19 UTC, tmtmtmtm requested changes

2016-10-05 08:19 UTC, tmtmtmtm commented on lib/everypolitician/popolo/event.rb
> +    class Event < EntityWithDynamicMethods
https://github.com/everypolitician/everypolitician-popolo/issues/56 should mean that Event doesn't need to go through this indirection — the work on that class has already been done.

It does, however, also raise the question as to why this approach is needed for some classes yet wasn't there. I don't quite understand what's going on here well enough yet to know understand that, I'm afraid.

2016-10-13 08:42 UTC, tmtmtmtm commented
@struan / @ondenman I'm assuming this one can also now be closed?

2016-10-13 08:47 UTC, ondenman commented
Closed in favour of: #99

2016-10-13 08:47 UTC, closed without merging